# This is the basic workflow to build release documentation

# !NOTE:
# This build is specifically for Version 1 i.e. JDF 
# It is triggered by a push of a tag that starts with '1', i.e. 1.9, or 1.14-IP3 etc
name: JDF Release Build

## This section contains ALL variable specific for this project
env:
  BUILD_NAME:       JDF-SPECIFICATION
  #JDF_DOCUMENT_VERSION:     '1.9' not required for release build. Uses Tag of build.
  JDF_DOCUMENT_COVER_TITLE:   JDF Specification
  JDF_CONFIG_FILE:          Build\JDF_Specification.ini

  CONFLUENCE_ID:        '1560313992'
  JDF_CONFLUENCE_LABELS:    'jdf-specification,milestone'
  
  DOCUMENT_METADATA_COPYRIGHT:  'CIP4 Organization, all rights reserved'
  DOCUMENT_JDF_METADATA_TITLE:  'JDF Specification'

  BUILD_UTILITY_EXE: c:\actions-runner\_work\_tool\document-processing\document-processing.exe   

# Controls when the action will run - the tag must start with a '1'
on:
  push:
    tags:
      - '1*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_jdf:
    runs-on: [framemaker-2020]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # For access to other Git repositories - an access token is required. 
      - name: Get GitHub Access Token
        id: access_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_KEY }} 
      
      # Clean up working directory
      - name: Clean up working directory
        run:  rm -r -fo *
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          path: document

      # Check out the build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v5
        with:
          repository: cip4/cip4-document-builder
          token: ${{ steps.access_token.outputs.token }}
          path: builder

      # Build the release document
      - name: Build Document
        timeout-minutes: 45
        run: >
          python ..\builder\scripts\specbuilder.py $env:JDF_CONFIG_FILE
          "$env:JDF_DOCUMENT_COVER_TITLE $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "$env:JDF_DOCUMENT_COVER_TITLE"
          "Version $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "$env:DOCUMENT_JDF_METADATA_TITLE $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "$(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "$((Get-Date).ToString('MMMM yyyy')) $env:DOCUMENT_METADATA_COPYRIGHT"
          "2000-$((Get-Date).ToString('yyyy'))"
          "Run-$env:GITHUB_RUN_NUMBER"
        working-directory: ./document
        
      # Upload any artefact produced.
      - name: Upload Document
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: document/target/*.pdf

      # Generate full Confluence Labels List
      - name: Generate Full Confluence Labels List
        run: >
          echo "FULL_CONFLUENCE_LABELS=${env:JDF_CONFLUENCE_LABELS},$(${env:GITHUB_REF}.replace('refs/tags/',''))" | 
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://cip4.atlassian.net/wiki'
          username: ${{ secrets.ATLASSIAN_USER }}
          password: ${{ secrets.ATLASSIAN_TOKEN }}
          contentId: ${{ env.CONFLUENCE_ID }}
          label:    ${{ env.FULL_CONFLUENCE_LABELS }}
          filePattern: 'document/target/*.pdf'
