# This is the basic workflow to build release documentation

# !NOTE:
# This build produces multiple versions of this document!!
name: Release Build
## This section contains ALL variable specific for this project ##
# The VERSION is the main release number i.e. 1.7 or 2.1
env:
# Common to all builds    
  BUILD_NAME:       JDF-SPECIFICATION
# 'BOTH' version is not built for release
#
# 'JDF' parameters
  JDF_DOCUMENT_VERSION:     '1.8'
  JDF_DOCUMENT_FILE_NAME:   JDF Specification
  JDF_CONFIG_FILE:          Build\JDF_Specification.ini
  JDF_CONFLUENCE_LABELS:    'jdf-specification,milestone'
# 'XJDF' parameters
  XDF_DOCUMENT_VERSION:     '2.2'
  XJDF_DOCUMENT_FILE_NAME:  XJDF Specification
  XJDF_CONFIG_FILE:         Build\XJDF_Specification.ini
  XJDF_CONFLUENCE_LABELS:   'xjdf-specification,milestone'
# Same ID for all builds  
  CONFLUENCE_ID:        '15663320'
  
  DOCUMENT_COPYRIGHT:   'CIP4 Organization, all rights reserved'

  BUILD_UTILITY_EXE: c:\actions-runner\_work\_tool\document-processing\document-processing.exe   

## The remaining section is based upon those common to all draft documentation builds
## It has been modified to allow for three slightly different builds.

# Controls when the action will run
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_jdf:
    runs-on: [framemaker-2020]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # For access to other Git repositories - an access token is required. 
      - name: Get GitHub Access Token
        id: access_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_KEY }} 
      
      # Clean up working directory
      - name: Clean up working directory
        run:  rm -r -fo *
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: document

      # Check out the build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v2
        with:
          repository: cip4/cip4-document-builder
          token: ${{ steps.access_token.outputs.token }}
          path: builder

      - name: Build Document
        timeout-minutes: 120
        run: >
          python ..\builder\scripts\specbuilder.py $env:JDF_CONFIG_FILE
          "$env:JDF_DOCUMENT_FILE_NAME $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "Release $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "Run-$env:GITHUB_RUN_NUMBER"
        working-directory: ./document
        
      # Update document properties copyright
      - name: Update copyright
        run: >
          ${{ env.BUILD_UTILITY_EXE }} info "$env:JDF_DOCUMENT_FILE_NAME*.pdf"
          --copyright "$((Get-Date).ToString('MMMM yyyy')) $env:DOCUMENT_COPYRIGHT"
        working-directory: ./document/target

      # Upload any artefact produced.
      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: document/target/*.pdf

      # Generate full Confluence Labels List
      - name: Generate Full Confluence Labels List
        run: >
          echo "FULL_CONFLUENCE_LABELS=${env:JDF_CONFLUENCE_LABELS},$(${env:GITHUB_REF}.replace('refs/tags/',''))" | 
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://cip4.atlassian.net/wiki'
          username: ${{ secrets.ATLASSIAN_USER }}
          password: ${{ secrets.ATLASSIAN_TOKEN }}
          contentId: ${{ env.CONFLUENCE_ID }}
          label:    ${{ env.FULL_CONFLUENCE_LABELS }}
          filePattern: 'document/target/*.pdf'

  build_xjdf:
    runs-on: [framemaker-2020]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # For access to other Git repositories - an access token is required. 
      - name: Get GitHub Access Token
        id: access_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_ID }}
          private_key: ${{ secrets.CIP4_GITHUB_ACTIONS_APP_KEY }} 
      
      # Clean up working directory
      - name: Clean up working directory
        run:  rm -r -fo *
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: document

      # Check out the build scripts
      - name: Checkout build scripts
        uses: actions/checkout@v2
        with:
          repository: cip4/cip4-document-builder
          token: ${{ steps.access_token.outputs.token }}
          path: builder

      - name: Build Document
        timeout-minutes: 120
        run: >
          python ..\builder\scripts\specbuilder.py $env:XJDF_CONFIG_FILE
          "$env:XJDF_DOCUMENT_FILE_NAME $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "Release $(${env:GITHUB_REF}.replace('refs/tags/',''))"
          "Run-$env:GITHUB_RUN_NUMBER"
        working-directory: ./document
        
      # Update document properties copyright
      - name: Update copyright
        run: >
          ${{ env.BUILD_UTILITY_EXE }} info "$env:XJDF_DOCUMENT_FILE_NAME*.pdf"
          --copyright "$((Get-Date).ToString('MMMM yyyy')) $env:DOCUMENT_COPYRIGHT"
        working-directory: ./document/target

      # Upload any artefact produced.
      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: document/target/*.pdf

      # Generate full Confluence Labels List
      - name: Generate Full Confluence Labels List
        run: >
          echo "FULL_CONFLUENCE_LABELS=${env:XJDF_CONFLUENCE_LABELS},$(${env:GITHUB_REF}.replace('refs/tags/',''))" | 
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://cip4.atlassian.net/wiki'
          username: ${{ secrets.ATLASSIAN_USER }}
          password: ${{ secrets.ATLASSIAN_TOKEN }}
          contentId: ${{ env.CONFLUENCE_ID }}
          label:    ${{ env.FULL_CONFLUENCE_LABELS }}
          filePattern: 'document/target/*.pdf'
