# This is the basic workflow to build the draft JDF, XJDF & Both Specifications

name: Snapshot Build
# The VERSION is the main release number i.e. 1.8 or 2.1
env:      
  BUILD_NAME:       JDF-Specifications
  BOTH_VERSIONS:    '1.8+2.2'
  JDF_VERSION:      '1.8'
  XJDF_VERSION:     '2.2'
  BOTH_FILE_NAME:   BOTH Specifications
  BOTH_CONFIG_FILE: BOTH_Specifications.ini  
  JDF_FILE_NAME:    JDF Specification
  JDF_CONFIG_FILE:  JDF_Specification.ini
  XJDF_FILE_NAME:   XJDF Specification
  XJDF_CONFIG_FILE: XJDF_Specification.ini

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Run'  
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  
  build-both:
    # The type of runner that the job will run on
    runs-on: [framemaker-2020]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      # Get the date 
      - name: Get current time/date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDD

      # Uses the remote self-host to build the ICS
      - name: Build Both Specification
        # Set local environment variables - of course these could be set directly, but...
        env:
          NOW: "${{ steps.current-time.outputs.formattedTime }}"
          version:      ${{env.BOTH_VERSIONS}}
          filename:     ${{env.BOTH_FILE_NAME}} 
          configfile:   ${{env.BOTH_CONFIG_FILE}}
        run:  >
          python Build\specbuilder.py $env:configfile
          "$env:filename $env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "$env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "Run-$env:GITHUB_RUN_NUMBER"

      # Upload any artefact produced.
      - name: Upload Specification
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: target/*.pdf
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://confluence.cip4.org'
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_PASSWORD }}
          contentId: 15663320
          label: 'both-specificaion,spec-draft'
          filePattern: 'target/*.pdf'
 
  build-jdf:
    # The type of runner that the job will run on
    runs-on: [framemaker-2015]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      # Get the date 
      - name: Get current time/date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDD

      # Uses the remote self-host to build the ICS
      - name: Build JDF Specification
        env:
          NOW: "${{ steps.current-time.outputs.formattedTime }}"
          version:      ${{env.JDF_VERSION}}
          filename:     ${{env.JDF_FILE_NAME}} 
          configfile:   ${{env.JDF_CONFIG_FILE}}
        run: >
          python Build\specbuilder.py $env:configfile
          "$env:filename $env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "$env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "Run-$env:GITHUB_RUN_NUMBER"

      # Upload any artefact produced.
      - name: Upload Specification
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: target/*.pdf
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://confluence.cip4.org'
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_PASSWORD }}
          contentId: 15663320
          label: 'jdf-specificaion,spec-draft'
          filePattern: 'target/*.pdf'        
          
  build-xjdf:
    # The type of runner that the job will run on
    runs-on: [framemaker-2015]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source
        uses: actions/checkout@v2

      # Get the date 
      - name: Get current time/date
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDD

      # Uses the remote self-host to build the ICS
      - name: Build XJDF Specification
        env:
          NOW: "${{ steps.current-time.outputs.formattedTime }}"
          version:      ${{env.XJDF_VERSION}}
          filename:     ${{env.XJDF_FILE_NAME}} 
          configfile:   ${{env.XJDF_CONFIG_FILE}}
        run: >
          python Build\specbuilder.py $env:configfile
          "$env:filename $env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "$env:version DRAFT-$env:NOW Build-$env:GITHUB_RUN_NUMBER"
          "Run-$env:GITHUB_RUN_NUMBER"

      # Upload any artefact produced.
      - name: Upload Specification
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-artifact
          path: target/*.pdf
          
      # Upload to Confluence
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://confluence.cip4.org'
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_PASSWORD }}
          contentId: 15663320
          label: 'xjdf-specificaion,spec-draft'
          filePattern: 'target/*.pdf'
